name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  set_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(grep -m 1 '"version"' manifest.json | sed 's/[^0-9.]*//g')
          echo "::set-output name=VERSION::$VERSION"
          
  build_chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Zip chrome
        run: zip -qq -r chrome.zip *
      - uses: actions/upload-artifact@v3
        with:
          name: chrome
          path: chrome.zip

  build_firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: change manifest version
        run: |
          sed -i 's/manifest_version": 3/manifest_version": 2/' manifest.json
      - name: Zip firefox
        run: zip -qq -r firefox.zip *
      - uses: actions/upload-artifact@v3
        with:
          name: firefox
          path: firefox.zip

  publish_chrome:
    needs: build_chrome
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download extension
        uses: actions/download-artifact@v3
        with:
          name: chrome
      - name: Publish Chrome
        uses: wdzeng/chrome-extension@v1
        with:
          extension-id: efbkeonpffhkgplinehopofbjhmacpea
          zip-path: chrome.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

  publish_firefox:
    needs: build_firefox
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Download extension
        uses: actions/download-artifact@v3
        with:
          name: firefox
      - name: Publish Firefox
        uses: maoserr/firefox_extension_publish@v1.0.4
        with:
          firefox_extension_id: '{1d4f136b-eb8d-40ea-96d8-a932c5d4de83}'
          api_key: ${{ secrets.FIREFOX_API_KEY }}
          api_secret: ${{ secrets.FIREFOX_API_SECRET }}
          file: firefox.zip
         #src_file: src.zip

  publish_release:
    needs: [ build_firefox, build_chrome, set_version ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download extension
        uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.set_version.outputs.version }}_${{ github.run_number }}
          files: |
            firefox/firefox.zip
            chrome/chrome.zip
