name: Build and Publish

on:
  push:
    branches: [ main, dev ]

env:
  MAJOR_VER: 1
  MINOR_VER: 0

jobs:
  build_chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Zip chrome
        run: zip -qq -r chrome.zip *
      - uses: actions/upload-artifact@v3
        with:
          name: chrome
          path: chrome.zip

  build_firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: change manifest version
        run: |
          sed -i 's/manifest_version": 3/manifest_version": 2/' manifest.json
      - name: Zip firefox
        run: zip -qq -r firefox.zip *
      - uses: actions/upload-artifact@v3
        with:
          name: firefox
          path: firefox.zip

  publish_chrome:
    needs: build_chrome
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download extension
        uses: actions/download-artifact@v3
        with:
          name: chrome
      - name: Publish Chrome
        uses: maoserr/chrome_extension_publish@v1.0.3
        with:
          chrome_extension_id: efbkeonpffhkgplinehopofbjhmacpea
          client_id: ${{ secrets.CHROME_CLIENT_ID }}
          refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          file: chrome.zip

  publish_firefox:
    needs: build_firefox
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Download extension
        uses: actions/download-artifact@v3
        with:
          name: firefox
      - name: Publish Firefox
        uses: maoserr/firefox_extension_publish@v1.0.4
        with:
          firefox_extension_id: epublifier@maoserr.com
          api_key: ${{ secrets.FIREFOX_API_KEY }}
          api_secret: ${{ secrets.FIREFOX_API_SECRET }}
          file: firefox.zip
         #src_file: src.zip

  publish_release:
    needs: [ build_firefox, build_chrome ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download extension
        uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ github.run_number }}
          files: |
            firefox/firefox.zip
            chrome/chrome.zip